### ISSUE TITLE
youtube tutorial for simulator instalation?

### ISSUE THREAD

**Issue by TucudeanAdrian** [FieldRobotEvent/Virtual_Field_Robot_Event#17]
would be a great help if u can do that

**Comment by ThijsRuigrok** [comment]
We are currently still working on improving the simulator. Therefore, instructions for installation can change as well. We therefore do not have a youtube tutorial for the installation. Please contact us if you need help with specific parts of the installation.

**Comment by ThijsRuigrok** [comment]
The installation instructions are updated and should now be more clear. Hope this helps.

**Comment by TucudeanAdrian** [comment]
ok , thanks so far!
