### ISSUE TITLE
Sample driving pattern is not possible

### ISSUE THREAD

**Issue by Darkproduct** [FieldRobotEvent/Virtual_Field_Robot_Event#52]
The current driving pattern: `S 3L 2L 2R 1R 5L F`
![image](https://user-images.githubusercontent.com/35309884/120694315-55ecd180-c4aa-11eb-9380-0542d9ec409e.png)

Side note:
The delimiter is `[space]` and not `[space]-[space]` as suggested in the [Task 2 description](https://www.fieldrobot.com/event/index.php/contest/task-2/).

**Comment by ThijsRuigrok** [comment]
Hi, 

Tnx. for pointing this out. I changed the driving pattern to `S 3L 2L 1R 1R 5L F` to make it a valid pattern :).

Also I can confirm that we now use `[space]` as a delimiter. I will request to update the website :).
