### ISSUE TITLE
FRE Logo not visible in Readme

### ISSUE THREAD

**Issue by Darkproduct** [FieldRobotEvent/Virtual_Field_Robot_Event#53]
Someone updated the FRE Logo to Version 3 on the Website and deleted Version 2, therefore the Logo is not visible in the main readme and the virtual_maize_field readme.

Old URL: https://www.fieldrobot.com/event/wp-content/uploads/2021/01/FRE-logo-v02.png
New URL: https://www.fieldrobot.com/event/wp-content/uploads/2021/05/FRE-logo-v03.png

I would suggest to make those updates in-place, then everything will be updated accordingly.

**Comment by ThijsRuigrok** [comment]
Tnx! I changed the links!
